# Generated by Django 2.2.3 on 2019-08-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('city', models.CharField(max_length=84, null=True)),
                ('mobile', models.CharField(max_length=84, null=True)),
            ],
        ),
    ]
