# Generated by Django 2.2.3 on 2019-09-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='', max_length=84, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(default='', max_length=84, null=True),
        ),
    ]
